### ISSUE TITLE
Issue when running for the first time

### ISSUE THREAD

**Issue by joshghent** [jacc/music-box#10]
Hey there!
Thanks for the awesome tool, you've inspired me to make my own that uses rescuetime data 👍 

Wanted to raise a bit of an issue with getting it working though. Please see the error below. Let me know if you need any more info 👍 

![Screenshot 2019-10-30 at 09 55 08](https://user-images.githubusercontent.com/2934976/67847852-7baa3b80-fafb-11e9-9a38-5d3f7962725f.png)

**Comment by jacc** [comment]
Hey Josh!

Super happy to hear that I was able to inspire to you get out and explore with the Gists API. I just pushed a commit that should fix GitHub Actions (been super busy with school so I've personally been using CircleCI, I'll update this issue if it runs all okay.)

**Comment by casperdcl** [comment]
Fixed in #15 :)

**Comment by casperdcl** [comment]
Actually fixed in #16 :)
