### ISSUE TITLE
Shorter width for new GitHub UI

### ISSUE THREAD

**Issue by AnandChowdhary** [jacc/music-box#20]
After the GitHub UI update with more padding in featured repos/gists, my musicbox looks like this:

![Screen Shot 2020-06-27 at 2 32 12 AM](https://user-images.githubusercontent.com/2841780/85900975-68807480-b81e-11ea-8b24-dfa403d04000.png)

Maybe we can decrease the width of the text, perhaps have it configurable?

**Comment by jacc** [comment]
![image](https://user-images.githubusercontent.com/6956351/85902610-6e506880-b7d2-11ea-96be-82b2199c045b.png)

i can't seem to reproduce this? are you sure it's not a matter of screen size/resolution?

as for having it be configurable, i'm going to eventually rewrite the entire project in js/ts and have it have different configurable options :)-

**Comment by alii** [comment]
A ts rewrite would be awesome!

**Comment by jacc** [comment]
@aabbccsmith soon ;)

**Comment by AnandChowdhary** [comment]
> i can't seem to reproduce this? are you sure it's not a matter of screen size/resolution?

Could be. Do you think you can see my profile and show me what it looks like on your device? https://github.com/AnandChowdhary

**Comment by jacc** [comment]
![image](https://user-images.githubusercontent.com/6956351/85928590-0ce4d400-b87c-11ea-9ec1-2218dc72b890.png)

seems to be all good on my end

**Comment by AnandChowdhary** [comment]
Thanks, @jacc! It's probably just me: I'm using Safari on macOS and it's been like this since the GitHub UI update.

**Comment by jacc** [comment]
@AnandChowdhary all good! last question, do you happen to be on big sur? wondering if that's the issue

**Comment by AnandChowdhary** [comment]
No, just Safari 13.1.1 (15609.2.9.1.2) on macOS Catalina 10.15.5 (19F101).
