### ISSUE TITLE
imperfect alignment due to Asian language 

### ISSUE THREAD

**Issue by Boycottangent** [jacc/music-box#5]
The alignment has bug if text contains Asian language word like Japanese or Chinese.

```
ヒトリエ            ███████████████████████░░░░     75 plays
Polyphia        ████████████████░░░░░░░░░░░     50 plays
CHON            █████████████░░░░░░░░░░░░░░     43 plays
草東沒有派對          ██████░░░░░░░░░░░░░░░░░░░░░     18 plays
amazarashi      █████░░░░░░░░░░░░░░░░░░░░░░     16 plays
```

Sorry that I'm not a programmer so not able to handle this, hope you can fix it.

**Comment by jacc** [comment]
Hey there, thanks for letting me know about this. I'll look into fixing this when I have the time.
